#!/bin/bash
# -*- mode: shell-script-mode; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
#
# Copyright (C) 2012-13 O.S. Systems Software LTDA.
# Copyright (C) 2017 Open Source Foundries Ltd.
# Copyright (C) 2020-2026 Toradex AG
# Authored-by:  Otavio Salvador <otavio@ossystems.com.br>
# Adopted to Angstrom:  Khem Raj <raj.khem@gmail.com>
#
# SPDX-License-Identifier: GPL-2.0-only
#

[ -z "${SDKMACHINE}" ] && SDKMACHINE='x86_64'

# resolve/export BUILDDIR ourselves, then rebuild PATH and
# BB_ENV_PASSTHROUGH_ADDITIONS.
tdx_set_builddir "${1:-}" "${DISTRO}" || return 1
tdx_setup_path
tdx_setup_bb_env_passthrough

# Early-return if MACHINE/DISTRO/script-checksum are all unchanged.
tdx_native_conf_is_current && return 0

tdx_write_checksum "${_TDX_SCRIPTS}/lib/setup-devices/setup-environment-nvidia"

tdx_conf_from_template local.conf

tdx_append_once conf/bblayers.conf "# Torizon" <<EOF
# Torizon
# LAYER_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
LCONF_VERSION = "7"
OEROOT := "\${@os.path.abspath(os.path.dirname(d.getVar('FILE', True)))}/../.."

BBPATH = "\${TOPDIR}"

BBFILES = ""

# These layers hold recipe metadata not found in OE-core, but lack any machine or distro content
BASELAYERS ?= " \\
  \${OEROOT}/layers/meta-openembedded/meta-oe \\
  \${OEROOT}/layers/meta-openembedded/meta-networking \\
  \${OEROOT}/layers/meta-openembedded/meta-filesystems \\
  \${OEROOT}/layers/meta-openembedded/meta-python \\
  \${OEROOT}/layers/meta-openembedded/meta-perl \\
  \${OEROOT}/layers/meta-virtualization \\
  \${OEROOT}/layers/meta-updater \\
  \${OEROOT}/layers/meta-cyclonedx \\
  \${OEROOT}/layers/meta-security \\
"

# These layers hold machine specific content, aka Board Support Packages
BSPLAYERS ?= " \\
  \${OEROOT}/layers/meta-yocto/meta-yocto-bsp \\
  \${OEROOT}/layers/meta-yocto/meta-poky \\
  \${OEROOT}/layers/meta-security \\
  \${OEROOT}/layers/meta-tegra \\
"

# Add your overlay location to EXTRALAYERS
# Make sure to have a conf/layers.conf in there
EXTRALAYERS ?= ""

BBLAYERS = " \\
  \${OEROOT}/layers/meta-torizon-bsp \\
  \${OEROOT}/layers/meta-torizon \\
  \${BASELAYERS} \\
  \${BSPLAYERS} \\
  \${EXTRALAYERS} \\
  \${OEROOT}/layers/openembedded-core/meta \\
"
EOF

ln -sf "${_TDX_MANIFESTS}/README.md" README.md
ln -sf "${_TDX_MANIFESTS}" "${_TDX_OEROOT}/layers/"

tdx_write_auto_conf "${DISTRO}" "${MACHINE}" "${SDKMACHINE}" "rm_work cyclonedx-export"
tdx_apply_integration_override conf/auto.conf

tdx_write_site_conf "${_TDX_OEROOT}" "${_TDX_BUILDDIR}"

tdx_print_banner "Common Torizon OS" yes
